// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://placeholder.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'placeholder-anon-key';

// True only when real credentials are present. When false, cloud-dependent
// features (side-judge sync, tournament cloud save, etc.) should be treated
// as unavailable, but the app itself must never crash on startup because of
// this — a packaged Electron build has no .env file unless one was baked in
// at build time, and the previous behavior (throwing at import time) blacked
// out the entire app before React could even render.
export const isSupabaseConfigured = Boolean(
  import.meta.env.VITE_SUPABASE_URL && import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// ---------------------------------------------------------------------------
// Supabase production authentication
// ---------------------------------------------------------------------------
// Realtime judge/broadcast channels need an authenticated Supabase session.
// The side-judge flow has no Supabase password/login screen, so when there is
// no existing real session we bootstrap an ANONYMOUS session for Realtime.
// This restores the behaviour that the judge connection relied on before the
// final RLS hardening.
//
// This does NOT weaken the production database-write policies: the final RLS
// migration explicitly rejects JWTs with is_anonymous=true for INSERT/UPDATE/
// DELETE. Anonymous auth is used here only to satisfy the existing
// `realtime.messages` policy (TO authenticated) so judge-votes/match-sync can
// subscribe and broadcast. Real operator writes still require a real
// Supabase-authenticated account carrying app_metadata.role.
//
// A real Supabase session is always preferred. Anonymous auth is only the
// fallback needed by the judge/broadcast channel because those screens have no
// Supabase login form. Database DML remains blocked for anonymous JWTs by RLS.
const allowAnonymousRealtime = true;

export async function ensureRealtimeSession() {
  if (!isSupabaseConfigured) return null;
  const { data } = await supabase.auth.getSession();
  if (data.session) return data.session;
  if (!allowAnonymousRealtime) return null;
  const { data: anon, error } = await supabase.auth.signInAnonymously();
  if (error) {
    console.warn('[supabase] anonymous realtime session failed:', error.message);
    return null;
  }
  return anon.session;
}

if (isSupabaseConfigured && allowAnonymousRealtime) {
  void ensureRealtimeSession().catch((error) => {
    console.warn('[supabase] realtime auth bootstrap failed:', error);
  });
}
